name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '15 17 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.repository == 'BlueBoxWare/steamdb'
    steps:
      - uses: actions/checkout@v4
      - name: Update data
        run: python scripts/fetch.py data/ 500
      - name: Update lists
        run: python scripts/create_lists.py data/ lists/
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update'
          push: origin main --force
